version: "3.7"
services:
  staff_schedule_service:
    image: "staffscheduleing:1.0"
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo_db:app_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017